# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ripser
#' 
#' Run ripser 
#' 
#' @param dist_mat distance matrix
#' @param dim compute persistent homology up to this dimension 
#' @param threshold compute Rips complex up to this diameter
#' @examples
#' rcircle <- function(N, r = 1, sd = 0){
#' radius <- rnorm(N, r, sd)
#' angle <- runif(N, 0, 2*pi)
#' data.frame(x = radius * cos(angle), 
#'            y = radius * sin(angle))
#' }
#' dta <- rcircle(200, sd = 0.1)
#' dmat <- as.matrix(dist(dta))
#' pers <- run_ripser(dmat, dim = 2)
#' @export
run_ripser <- function(dist_mat, dim = 1L, threshold = NA_real_) {
    .Call(`_Rripser_run_ripser`, dist_mat, dim, threshold)
}

